[package]
name = "vlazed/fespiderman"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
TableUtil = "sleitnick/table-util@1.1.5"
Signal = "sleitnick/signal@1.2.1"

[dev-dependencies]
testez = "roblox/testez@0.4.1"